stages:
  - build

variables:
  IMAGE_NAME: "landing:latest"
  REGISTRY_URL: "repo.grsx.ru:5005/vdsvps/site/landing-page"

before_script:
  - docker info
# tags:
#   - site 

build:
  stage: build
  tags: 
    - site 
  script:
    - docker build -t landing:1.0 .

# docker build -t landing:1.0 .
# docker run -d -p 3000:3000 -t landing:1.0 --name landing
# docker login repo.grsx.ru:5005
# docker tag landing:1.0 repo.grsx.ru:5005/vdsvps/site/landing-page/landing/landing:1.0
# docker push repo.grsx.ru:5005/vdsvps/site/landing-page/landing/landing:1.0

