stages:
  - build

before_script:
  - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t land:latest .
    - docker tag land:latest $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker rm -f landing || true
    - docker run --name landing -d -p 3000:3000 -t land:latest
    - docker rmi -f $(docker images -q)  || true
  tags:
    - site
#1
